Feat : DIG-60 팔로우, 언팔로우 구현
Goorm-OGJG/Da-It-Gym-BE pull request #12
Opened 2023-11-02 13:51 UTC by Dongjin113

### 팔로우 구현
- 존재하지 않는 회원이면 Exception 반환
- 이미 팔로우 되어있으면 AlreadyFollowUser Exception 반환

### 언팔로우 구현
- 존재하지 않는 회원이면 Exception 반환
- 이미 팔로우 안되어 있으면 NotFoundFollow Exception 반환

2023-11-02 16:37 UTC, dunowljj requested changes

2023-11-02 16:37 UTC, dunowljj commented on src/main/java/com/ogjg/daitgym/follow/service/FollowService.java
> +    }
누락된 @Trancsactional 추가 부탁드려요!

2023-11-02 16:37 UTC, dunowljj commented on src/main/java/com/ogjg/daitgym/follow/repository/FollowRepository.java
> +    int countByFollowPKTargetEmail(String targetEmail);
혹시 `countByFollowPKTargetEmail` 이부분은 FollowPK 에 있는 TargetEmail을 기준으로 카운트 한다는건가요?

2023-11-02 16:37 UTC, dunowljj commented on src/main/java/com/ogjg/daitgym/follow/service/FollowService.java
> +        return new FollowCountResponse(followingCount);
혹시 인라인으로 해서 요런 포맷팅은 어떠신가요?
```java
return new FollowCountResponse(
    followRepository.countByFollowPKFollowerEmail(user.getEmail())
);
```

2023-11-02 16:37 UTC, dunowljj commented on src/main/java/com/ogjg/daitgym/follow/service/FollowService.java
> +        findFollowByFollowPK(followPK);
Follow 여부를 검사하는 로직이라면, 메서드 명을 기능에 맞게 바꿔주시면 좋을 것 같습니다!!

2023-11-02 16:38 UTC, dunowljj commented
팔로우 구현맡아주셔서 
감사합니다 동진님 
감사합니다 동진님 
감사합니다 동진님
🙏

2023-11-03 01:18 UTC, Dongjin113 commented on src/main/java/com/ogjg/daitgym/follow/service/FollowService.java
> +        return new FollowCountResponse(followingCount);
너무 길어서 일부러 위에서 변수명으로 지정해주고 썻습니다

2023-11-03 01:19 UTC, Dongjin113 commented on src/main/java/com/ogjg/daitgym/follow/service/FollowService.java
> +        findFollowByFollowPK(followPK);
여기에서는 검사하는 의미로 사용하지만 이메서드에서 검사하는 의미이지 다른곳에서 사용한다면 조회의 의미도 있을것같아서 저렇게 사용했습니다

2023-11-03 01:19 UTC, Dongjin113 commented on src/main/java/com/ogjg/daitgym/follow/repository/FollowRepository.java
> +    int countByFollowPKTargetEmail(String targetEmail);
네

2023-11-03 01:19 UTC, Dongjin113 commented on src/main/java/com/ogjg/daitgym/follow/service/FollowService.java
> +    }
조회부분이라 필요하다고 생각안해서 안썻는데 조회부분에도 Transactional readOnly로 사용하는게 좋을까요?

2023-11-03 01:56 UTC, dunowljj commented on src/main/java/com/ogjg/daitgym/follow/service/FollowService.java
> +        return new FollowCountResponse(followingCount);
좋습니다!!

2023-11-03 01:56 UTC, dunowljj commented on src/main/java/com/ogjg/daitgym/follow/service/FollowService.java
> +    }
넵 그게 성능상 이점이 있는걸로 알고있습니다.

2023-11-03 02:04 UTC, Dongjin113 commented on src/main/java/com/ogjg/daitgym/follow/service/FollowService.java
> +    }
작업자가 아닌 다른 사람이 볼때도 좋을것 같네요

2023-11-03 03:16 UTC, dunowljj commented on src/main/java/com/ogjg/daitgym/follow/service/FollowService.java
> +        findFollowByFollowPK(followPK);
그렇군요! 저는 분리하는 것을 선호하는 편이긴합니다! 고생하셨습니다!

2023-11-03 03:16 UTC, dunowljj approved these changes

2023-11-03 07:55 UTC, merged