Feat : DIG-70 좋아요 기능 구현
Goorm-OGJG/Da-It-Gym-BE pull request #14
Opened 2023-11-03 14:27 UTC by YEJINGO

- RoutineLike 구현 : 루틴 좋아요/좋아요취소 시, 총 좋아요 개수 함께 반환
- FeedExerciseJournalLike 구현 : 피드 운동일지 좋아요/좋아요취소 시, 총 좋아요 개수 함께 반환
- FeedExerciseJournalLike 복합키 수정 : ExerciseJournalLikePk -> FeedExerciseJournalLikePk
- ErrorCode 수정 : 400 -> 404로 수정

2023-11-04 07:40 UTC, Dongjin113 requested changes
수고하셨습니다~

2023-11-04 07:40 UTC, Dongjin113 commented on src/main/java/com/ogjg/daitgym/like/feedExerciseJournal/dto/FeedExerciseJournalLikeResponse.java
> +public class FeedExerciseJournalLikeResponse {
음 다른 개발자가 실수로 빈객체를 생성하는것을 방지하기위해서 accessLevel을 Protected로 설정하는건 어떨까요?

2023-11-04 07:40 UTC, Dongjin113 commented on src/main/java/com/ogjg/daitgym/like/feedExerciseJournal/repository/FeedExerciseJournalLikeRepository.java
> +
좋아요를 누른 사용자가 몇명인지는 이걸호출하면되는거죠?

2023-11-04 07:40 UTC, Dongjin113 commented on src/main/java/com/ogjg/daitgym/like/feedExerciseJournal/repository/FeedExerciseJournalLikeRepository.java
> +    boolean existsByEmail(String email);
이메일을 통해 사용자가 누른 모든 좋아요 목록을 가져와서
그 목록이 0보다 크다면 true를 작다면 false를 반환하는 쿼리문인가요?

email로만 검색을하면 사용자가 누른 모든 목록을 불러와서 사용자가 여러 게시글을 좋아요를 눌렀다면 항상
false를 반환할 것 같은데 의도하신걸까요?

@Param Annotation이 없어도 Query문에서 사용이 되나요???

2023-11-04 07:40 UTC, Dongjin113 commented on src/main/java/com/ogjg/daitgym/like/feedExerciseJournal/service/FeedExerciseJournalLikeService.java
> +        }
likeCount++를 통해 likeCount를 보내준다면 동시에 여러명이 좋아요를 누른다면 무조건 한개만 상승하지 않을까요??

2023-11-04 07:40 UTC, Dongjin113 commented on src/main/java/com/ogjg/daitgym/like/feedExerciseJournal/service/FeedExerciseJournalLikeService.java
> +        if (feedJournalLikeRepository.existsByEmail(user.getEmail())) {
이곳두요!

2023-11-04 08:05 UTC, Dongjin113 commented on src/main/java/com/ogjg/daitgym/like/feedExerciseJournal/service/FeedExerciseJournalLikeService.java
> +        }
동시성에대한 처리가 별도로 없다면 다시 조회해서 사용하는것이 더 좋지않을까요??
DB에 락을 건다던가 트랜잭션 격리 수준을 올린다거나?

2023-11-04 08:37 UTC, Dongjin113 commented on src/main/java/com/ogjg/daitgym/like/feedExerciseJournal/service/FeedExerciseJournalLikeService.java
> +        }
만약에 데이터를 저장하고 likeCount를 조회해온다고 해도 save는 영속성 컨텍스트에서만 저장이 된 상태고 DB에는 반영이 되어있지 않은 상태이기 떄문에  flush를 하고Count를 조회해야 할 것 같습니다

2023-11-05 10:50 UTC, YEJINGO commented on src/main/java/com/ogjg/daitgym/like/feedExerciseJournal/dto/FeedExerciseJournalLikeResponse.java
> +public class FeedExerciseJournalLikeResponse {
네 수정해놓겠습니다!

2023-11-05 10:53 UTC, YEJINGO commented on src/main/java/com/ogjg/daitgym/like/feedExerciseJournal/repository/FeedExerciseJournalLikeRepository.java
> +
네 맞아요.
그런데, entity에서 feedExerciseJournal의 column 이름을 journalId로 잘못 만들어서 변수명 변경했습니다.
**int countByFeedJournalLikePkFeedExerciseJournalId(Long feedJournalId);**

2023-11-05 11:02 UTC, YEJINGO commented on src/main/java/com/ogjg/daitgym/like/feedExerciseJournal/repository/FeedExerciseJournalLikeRepository.java
> +    boolean existsByEmail(String email);
- @param  어노테이션 없이도 쿼리문에서 사용됩니다.
- email로만 가져오지 않고, feedExerciseJournalId도 일치하는 값으로 가져오는걸로 수정하겠습니다.
- true,false는 단순히 이메일에 해당하는 엔티티가 존재하는지 여부 확인하려고 작성한건데 필요 없을 것 같습니다.(boolean existsByEmail(String email) 삭제

2023-11-05 11:03 UTC, YEJINGO commented on src/main/java/com/ogjg/daitgym/like/feedExerciseJournal/service/FeedExerciseJournalLikeService.java
> +        }
알려주셔서 감사합니다 동진님!
 int likeCount = feedJournalLikeRepository.countByFeedJournalLikePkExerciseJournalId(journalId);
이부분으로 count 조회하도록 수정하겠습니다.

2023-11-05 15:44 UTC, Dongjin113 commented on src/main/java/com/ogjg/daitgym/like/feedExerciseJournal/repository/FeedExerciseJournalLikeRepository.java
> +    boolean existsByEmail(String email);
감사합니다

2023-11-05 15:50 UTC, Dongjin113 approved these changes
수고하셨습니다~

2023-11-05 16:04 UTC, dunowljj approved these changes
고생하셨습니다~

2023-11-05 16:14 UTC, merged